name: JD-sign-action

on:
  repository_dispatch:
  release:
    types: published
  push:
    branches:
      - main
#  schedule:
#    - cron: 2 22 * * *
#    - cron: 3 23 * * *
  watch:
    types: started
    
env:
  JD_COOKIE: ${{ secrets.JD_COOKIE }}
  JD_DUAL_COOKIE: ${{ secrets.JD_DUAL_COOKIE }}
  PUSH_KEY: ${{ secrets.PUSH_KEY }}

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout codes
              uses: actions/checkout@v2
              
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                node-version: '12.x'
                
            - name: Run install
              run: npm install
              
            - name: Run Script
              run: node jd_sign.js
              
            - name: 'Get Date'
              run: echo "ACTION_DATE=$(TZ=':Asia/Shanghai' date '+%Y-%m-%d %T')" >> $GITHUB_ENV
              
            - name: Send mail
              uses: dawidd6/action-send-mail@v2.5.0
              with:
                server_address: smtp.gmail.com
                server_port: 465
                username: ${{ secrets.MAIL_USERNAME }}
                password: ${{ secrets.MAIL_PASSWORD }}
                subject: Github Actions京东每日签到(${{ env.ACTION_DATE }})
                body: file://result.txt
                to: ${{ secrets.MAIL_LIST }}
                from: Github Actions
                content_type: text/html
                convert_markdown: true
                attachments: ./result.txt
                
            - name: Upload result file
              uses: actions/upload-artifact@main
              if: env.UPLOAD_BESULT_DIR == 'true'
              with:
                name: result
                path: ./*.txt

